### ISSUE TITLE
Pouca documentação sobre utils.sh

### ISSUE THREAD

**Issue by tomaz-suller** [SkyRats/ep-oo-template#2]
Um usuário novo pode não entender como usar a flag `--help`. O ideal seria listar no README todas as funcionalidades do script, e possivelmente incluir exemplos de uso.

**Comment by Gabrielchollet** [comment]
O que acha?

<hr>

### O que é um script bash?
Um script nada mais é do que um algoritmo projetado para realizar uma determindada tarefa, utilizando os comandos específicos do bash e os executáveis do sistema operacional.
Dessa forma, podemos atribuir a diferentes argumentos, diferentes caminhos pelo qual nosso script percorrerá e no contexto da nossa aplicação esses argumentos são justamente as flags e/ou diretórios que utilizaremos para automatizar os testes do nosso EP.
### Como utilizar o script?
Primeiramente, em caso de dúvida, utilize a flag `--help` ou `-h` para ter acesso a descrição das utilidades desse script com seus respectivos argumentos.
```bash
$ ./utils.sh –help
Utilizacao
./utils.sh [-h -r -t] [-vt] [-c | -C source_dir build_dir] [-b build_dir]
-h | --help
  Imprime esta mensagem
-r | --run
  Executa o programa compilado em C++
-t | --test
  Executa os testes fornecidos no diretorio test/
-vt | --verbose-test
  Executa os testes e mostra saida dos casos de falha
-c  source_dir build_dir
  Reanaliza os arquivos CMakeLists.txt
-C source_dir build_dir
  Reanaliza os arquivos CMakeLists.txt e habilita testes
-b | --build build_dir
  Compila os arquivos C++ para serem executados
--build-and-run build_dir
  Compila os arquivos C++ e executa o programa gerado
```

#### Funcionalidades:

<details>
<summary>Expandir</summary>

- `-r | --run`: Executa o programa compilado em C++;
- `-t | --test`: Executa os testes fornecidos no diretorio `test/`;
- `-vt | --verbose-test`: Executa os testes e mostra saida dos casos de falha;
- `-c source_dir build_dir`: Reanaliza os arquivos `CmakeLists.txt`;
- `-C source_dir build_dir`: Reanaliza os arquivos `CmakeLists.txt` e habilita testes;
- `-b | --build build_dir`: Compila os arquivos C++ para serem executados;
- `--build-and-run build_dir`: Compila os arquivos C++ e executa o programa gerado;

</details>

**Comment by tomaz-suller** [comment]
Acho que dá pra tirar essa parte que explica o que o script é - acho que foge um pouco do escopo. Também na parte de baixo dá pra tirar a parte de Funcionalidades, já que é redundante com o exempo do -h em cima. Última coisa: a flag é `-h` ou `--help` (o `-help` nem sabia que funcionava haha).

Fora isso está ótimo, dá pra fazer um PR e integrar isso ou modificar direto, aí fica com você. Adiciona uma subseção na seção Desenvolvimento e sucesso!
